# Generated by Django 5.0.6 on 2024-06-12 15:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoacademica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horarioFim',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horarioInicio',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='horarioFim',
            field=models.TimeField(default=datetime.time(12, 30, 11, 704404)),
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='horarioInicio',
            field=models.TimeField(default=datetime.time(12, 30, 11, 704379)),
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.sala'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='ofertaDisciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoacademica.ofertadisciplina'),
        ),
    ]
