# Generated by Django 5.0.6 on 2024-06-13 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(12, 36, 15, 37455)),
        ),
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(12, 36, 15, 37435)),
        ),
        migrations.CreateModel(
            name="ListaDeEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aluno", models.ManyToManyField(to="gestaoacademica.aluno")),
                (
                    "ofertaDisciplina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestaoacademica.ofertadisciplina",
                    ),
                ),
            ],
        ),
    ]
