# Generated by Django 5.0.6 on 2024-06-15 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(9, 23, 57, 828963)),
        ),
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(9, 23, 57, 828932)),
        ),
    ]
