# Generated by Django 5.0.6 on 2024-06-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoacademica', '0002_remove_disciplina_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='diaDaSemana',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='Nome da disciplina',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cargaHoraria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='diaDaSemana',
            field=models.TextField(choices=[('DOMINGO', 'Domingo'), ('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado')], default='DOMINGO'),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='horarioFim',
            field=models.TimeField(default=datetime.time(12, 32, 56, 662825)),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='horarioInicio',
            field=models.TimeField(default=datetime.time(12, 32, 56, 662769)),
        ),
    ]
