# Generated by Django 5.0.6 on 2024-06-13 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0003_alter_ofertadisciplina_horariofim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(12, 36, 37, 349108)),
        ),
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(12, 36, 37, 349087)),
        ),
    ]
