# Generated by Django 5.0.6 on 2024-06-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0004_alter_disciplina_horariofim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="cargaHoraria",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(16, 27, 9, 829596)),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(16, 27, 9, 829571)),
        ),
    ]
