# Generated by Django 5.0.6 on 2024-06-11 20:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoacademica', '0006_disciplina_capacidade_disciplina_dependencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSala', models.TextField()),
                ('capacidade', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='diaDaSemana',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horarioFim',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horarioInicio',
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='diaDaSemana',
            field=models.TextField(choices=[('DOMINGO', 'Domingo'), ('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado')], default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='horarioFim',
            field=models.TimeField(default=datetime.time(17, 24, 56, 901067)),
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='horarioInicio',
            field=models.TimeField(default=datetime.time(17, 24, 56, 901033)),
        ),
        migrations.AddField(
            model_name='participacao',
            name='ofertaDisciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.ofertadisciplina'),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.professor'),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.disciplina'),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.turma'),
        ),
        migrations.AddField(
            model_name='ofertadisciplina',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoacademica.sala'),
        ),
    ]
