# Generated by Django 5.0.6 on 2024-06-11 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestaoacademica",
            "0006_disciplina_capacidade_disciplina_dependencia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(19, 39, 12, 650888)),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(19, 39, 12, 650847)),
        ),
    ]
