# Generated by Django 5.0.6 on 2024-06-15 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0009_alter_ofertadisciplina_horariofim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(20, 39, 29, 526355)),
        ),
        migrations.AlterField(
            model_name="ofertadisciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(20, 39, 29, 526329)),
        ),
    ]
