# Generated by Django 5.0.6 on 2024-06-12 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0011_alter_disciplina_horariofim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(8, 44, 33, 720339)),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(8, 44, 33, 720307)),
        ),
    ]
