# Generated by Django 5.0.6 on 2024-06-12 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaoacademica", "0013_alter_disciplina_horariofim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="matriculaStatus",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="pagamentoStatus",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="registroAluno",
        ),
        migrations.AddField(
            model_name="aluno",
            name="prontuario",
            field=models.TextField(
                db_index=True,
                default="AP",
                unique=True,
                verbose_name="Registro do Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioFim",
            field=models.TimeField(default=datetime.time(10, 12, 4, 220060)),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="horarioInicio",
            field=models.TimeField(default=datetime.time(10, 12, 4, 220030)),
        ),
    ]
